apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-exam-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-exam-app
  template:
    metadata:
      labels:
        app: jenkins-exam-app
    spec:
      containers:
      - name: app
        image: jenkins-exam-app:9
        ports:
        - containerPort: 8000
